import './globals.css'
import { Poppins } from 'next/font/google'
import { Roboto } from 'next/font/google';

const pop = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-pop',
});

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='${pop.variable} font-pop ${roboto.variable} font-roboto'>{children}</body>
    </html>
  )
}
